### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by cv-lab-x** [yanyan-li/GeoGaussian#1]
hi, thanks for your great work, when will you release the codes? 
@yanyan-li

**Comment by yanyan-li** [comment]
Hi,  thanks for your interesting in GeoGaussian. 
We plan to release the system at the end of May.

**Comment by yanyan-li** [comment]
Hi, thanks for your interests in GeoGaussian.
We plan to release the system at the end of May.

**Comment by Sugar55888** [comment]
Looking forward to the release of the code!

**Comment by Dargonxzy** [comment]
Looking forward to the release of the code!
