### ISSUE TITLE
some bugs when build surface_align.cu

### ISSUE THREAD

**Issue by cv-lab-x** [yanyan-li/GeoGaussian#5]
[    line    }](https://github.com/yanyan-li/GeoGaussian/blob/c367b06c91c8d7c67ffeab517c86f1ef1c68b518/submodules/diff-gaussian-rasterization/surface_align.cu#L125)
some bugs when build surface_align @fred-lyu

`GeoGaussian/submodules/diff-gaussian-rasterization/surface_align.cu(163): error: expected a ";`

**Comment by yanyan-li** [comment]
thx, we have updated the version of surface_align.cu. 
please pull the code and reinstall submodules
